export type CitySuggestion = {
  id: number;
  label: string;
  city: string;
  region: string | null;
  country: string | null;
  lat: number;
  lng: number;
};

export const SPAIN_CITIES: CitySuggestion[] = [
  // ── Provincia de Alicante / Costa Blanca ──────────────────────────────────
  { id: 1, city: "Alicante", region: "Comunitat Valenciana", country: "España", label: "Alicante, Comunitat Valenciana, España", lat: 38.3452, lng: -0.4815 },
  { id: 2, city: "Benidorm", region: "Comunitat Valenciana", country: "España", label: "Benidorm, Comunitat Valenciana, España", lat: 38.5388, lng: -0.1318 },
  { id: 3, city: "Calpe", region: "Comunitat Valenciana", country: "España", label: "Calpe, Comunitat Valenciana, España", lat: 38.6447, lng: 0.0441 },
  { id: 4, city: "Altea", region: "Comunitat Valenciana", country: "España", label: "Altea, Comunitat Valenciana, España", lat: 38.5990, lng: -0.0503 },
  { id: 5, city: "Jávea", region: "Comunitat Valenciana", country: "España", label: "Jávea, Comunitat Valenciana, España", lat: 38.7855, lng: 0.1647 },
  { id: 6, city: "Dénia", region: "Comunitat Valenciana", country: "España", label: "Dénia, Comunitat Valenciana, España", lat: 38.8404, lng: 0.1059 },
  { id: 7, city: "Torrevieja", region: "Comunitat Valenciana", country: "España", label: "Torrevieja, Comunitat Valenciana, España", lat: 37.9786, lng: -0.6826 },
  { id: 8, city: "Orihuela", region: "Comunitat Valenciana", country: "España", label: "Orihuela, Comunitat Valenciana, España", lat: 38.0850, lng: -0.9457 },
  { id: 9, city: "Elche", region: "Comunitat Valenciana", country: "España", label: "Elche, Comunitat Valenciana, España", lat: 38.2669, lng: -0.6983 },
  { id: 10, city: "Santa Pola", region: "Comunitat Valenciana", country: "España", label: "Santa Pola, Comunitat Valenciana, España", lat: 38.1851, lng: -0.5577 },
  { id: 11, city: "Villajoyosa", region: "Comunitat Valenciana", country: "España", label: "Villajoyosa, Comunitat Valenciana, España", lat: 38.5050, lng: -0.2340 },
  { id: 12, city: "Finestrat", region: "Comunitat Valenciana", country: "España", label: "Finestrat, Comunitat Valenciana, España", lat: 38.5644, lng: -0.2097 },
  { id: 13, city: "Polop", region: "Comunitat Valenciana", country: "España", label: "Polop, Comunitat Valenciana, España", lat: 38.6124, lng: -0.1282 },
  { id: 14, city: "La Nucía", region: "Comunitat Valenciana", country: "España", label: "La Nucía, Comunitat Valenciana, España", lat: 38.6109, lng: -0.1166 },
  { id: 15, city: "Albir", region: "Comunitat Valenciana", country: "España", label: "Albir, Comunitat Valenciana, España", lat: 38.5701, lng: -0.0785 },
  { id: 16, city: "Moraira", region: "Comunitat Valenciana", country: "España", label: "Moraira, Comunitat Valenciana, España", lat: 38.6880, lng: 0.1275 },
  { id: 17, city: "Teulada", region: "Comunitat Valenciana", country: "España", label: "Teulada, Comunitat Valenciana, España", lat: 38.7247, lng: 0.1072 },
  { id: 18, city: "El Campello", region: "Comunitat Valenciana", country: "España", label: "El Campello, Comunitat Valenciana, España", lat: 38.4357, lng: -0.3957 },
  { id: 19, city: "San Juan de Alicante", region: "Comunitat Valenciana", country: "España", label: "San Juan de Alicante, Comunitat Valenciana, España", lat: 38.4032, lng: -0.4297 },
  { id: 20, city: "Mutxamel", region: "Comunitat Valenciana", country: "España", label: "Mutxamel, Comunitat Valenciana, España", lat: 38.4166, lng: -0.4621 },
  { id: 21, city: "Crevillente", region: "Comunitat Valenciana", country: "España", label: "Crevillente, Comunitat Valenciana, España", lat: 38.2418, lng: -0.8122 },
  { id: 22, city: "Aspe", region: "Comunitat Valenciana", country: "España", label: "Aspe, Comunitat Valenciana, España", lat: 38.3460, lng: -0.7706 },
  { id: 23, city: "Novelda", region: "Comunitat Valenciana", country: "España", label: "Novelda, Comunitat Valenciana, España", lat: 38.3796, lng: -0.7693 },
  { id: 24, city: "Petrer", region: "Comunitat Valenciana", country: "España", label: "Petrer, Comunitat Valenciana, España", lat: 38.4802, lng: -0.7737 },
  { id: 25, city: "Elda", region: "Comunitat Valenciana", country: "España", label: "Elda, Comunitat Valenciana, España", lat: 38.4777, lng: -0.7918 },
  { id: 26, city: "Villena", region: "Comunitat Valenciana", country: "España", label: "Villena, Comunitat Valenciana, España", lat: 38.6339, lng: -0.8668 },
  { id: 27, city: "Alcoy", region: "Comunitat Valenciana", country: "España", label: "Alcoy, Comunitat Valenciana, España", lat: 38.6976, lng: -0.4745 },
  { id: 28, city: "Cocentaina", region: "Comunitat Valenciana", country: "España", label: "Cocentaina, Comunitat Valenciana, España", lat: 38.7466, lng: -0.4426 },
  { id: 29, city: "Pego", region: "Comunitat Valenciana", country: "España", label: "Pego, Comunitat Valenciana, España", lat: 38.8467, lng: -0.1229 },
  { id: 30, city: "Ondara", region: "Comunitat Valenciana", country: "España", label: "Ondara, Comunitat Valenciana, España", lat: 38.8310, lng: 0.0354 },
  { id: 31, city: "Pedreguer", region: "Comunitat Valenciana", country: "España", label: "Pedreguer, Comunitat Valenciana, España", lat: 38.7877, lng: 0.0378 },
  { id: 32, city: "Gata de Gorgos", region: "Comunitat Valenciana", country: "España", label: "Gata de Gorgos, Comunitat Valenciana, España", lat: 38.7729, lng: 0.0800 },
  { id: 33, city: "Benissa", region: "Comunitat Valenciana", country: "España", label: "Benissa, Comunitat Valenciana, España", lat: 38.7115, lng: 0.0489 },
  { id: 34, city: "Senija", region: "Comunitat Valenciana", country: "España", label: "Senija, Comunitat Valenciana, España", lat: 38.7303, lng: 0.0891 },
  { id: 35, city: "Lliber", region: "Comunitat Valenciana", country: "España", label: "Lliber, Comunitat Valenciana, España", lat: 38.7379, lng: 0.0955 },
  { id: 36, city: "Benitachell", region: "Comunitat Valenciana", country: "España", label: "Benitachell, Comunitat Valenciana, España", lat: 38.7297, lng: 0.1671 },
  { id: 37, city: "Pilar de la Horadada", region: "Comunitat Valenciana", country: "España", label: "Pilar de la Horadada, Comunitat Valenciana, España", lat: 37.8720, lng: -0.7815 },
  { id: 38, city: "Rojales", region: "Comunitat Valenciana", country: "España", label: "Rojales, Comunitat Valenciana, España", lat: 38.0889, lng: -0.7209 },
  { id: 39, city: "Guardamar del Segura", region: "Comunitat Valenciana", country: "España", label: "Guardamar del Segura, Comunitat Valenciana, España", lat: 38.0878, lng: -0.6556 },
  { id: 40, city: "Pinoso", region: "Comunitat Valenciana", country: "España", label: "Pinoso, Comunitat Valenciana, España", lat: 38.4016, lng: -1.0317 },
  // ── Costa Cálida / Murcia ─────────────────────────────────────────────────
  { id: 41, city: "Murcia", region: "Región de Murcia", country: "España", label: "Murcia, Región de Murcia, España", lat: 37.9834, lng: -1.1299 },
  { id: 42, city: "Cartagena", region: "Región de Murcia", country: "España", label: "Cartagena, Región de Murcia, España", lat: 37.6060, lng: -0.9861 },
  { id: 43, city: "Águilas", region: "Región de Murcia", country: "España", label: "Águilas, Región de Murcia, España", lat: 37.4055, lng: -1.5836 },
  { id: 44, city: "Mazarrón", region: "Región de Murcia", country: "España", label: "Mazarrón, Región de Murcia, España", lat: 37.5990, lng: -1.3167 },
  { id: 45, city: "San Pedro del Pinatar", region: "Región de Murcia", country: "España", label: "San Pedro del Pinatar, Región de Murcia, España", lat: 37.8310, lng: -0.7952 },
  { id: 46, city: "Los Alcázares", region: "Región de Murcia", country: "España", label: "Los Alcázares, Región de Murcia, España", lat: 37.7441, lng: -0.8612 },
  { id: 47, city: "Lorca", region: "Región de Murcia", country: "España", label: "Lorca, Región de Murcia, España", lat: 37.6713, lng: -1.7041 },
  { id: 48, city: "San Javier", region: "Región de Murcia", country: "España", label: "San Javier, Región de Murcia, España", lat: 37.8065, lng: -0.8340 },
  { id: 49, city: "Torre-Pacheco", region: "Región de Murcia", country: "España", label: "Torre-Pacheco, Región de Murcia, España", lat: 37.7442, lng: -0.9538 },
  { id: 50, city: "Molina de Segura", region: "Región de Murcia", country: "España", label: "Molina de Segura, Región de Murcia, España", lat: 38.0568, lng: -1.2120 },
  // ── Comunitat Valenciana (resto) ──────────────────────────────────────────
  { id: 51, city: "Valencia", region: "Comunitat Valenciana", country: "España", label: "Valencia, Comunitat Valenciana, España", lat: 39.4699, lng: -0.3763 },
  { id: 52, city: "Castellón de la Plana", region: "Comunitat Valenciana", country: "España", label: "Castellón de la Plana, Comunitat Valenciana, España", lat: 39.9864, lng: -0.0513 },
  { id: 53, city: "Sagunto", region: "Comunitat Valenciana", country: "España", label: "Sagunto, Comunitat Valenciana, España", lat: 39.6805, lng: -0.2725 },
  { id: 54, city: "Gandía", region: "Comunitat Valenciana", country: "España", label: "Gandía, Comunitat Valenciana, España", lat: 38.9680, lng: -0.1823 },
  { id: 55, city: "Cullera", region: "Comunitat Valenciana", country: "España", label: "Cullera, Comunitat Valenciana, España", lat: 39.1631, lng: -0.2536 },
  { id: 56, city: "Oliva", region: "Comunitat Valenciana", country: "España", label: "Oliva, Comunitat Valenciana, España", lat: 38.9107, lng: -0.1186 },
  { id: 57, city: "Peñíscola", region: "Comunitat Valenciana", country: "España", label: "Peñíscola, Comunitat Valenciana, España", lat: 40.3623, lng: 0.4115 },
  { id: 58, city: "Vinaròs", region: "Comunitat Valenciana", country: "España", label: "Vinaròs, Comunitat Valenciana, España", lat: 40.4713, lng: 0.4740 },
  { id: 59, city: "Torrent", region: "Comunitat Valenciana", country: "España", label: "Torrent, Comunitat Valenciana, España", lat: 39.4330, lng: -0.4631 },
  { id: 60, city: "Paterna", region: "Comunitat Valenciana", country: "España", label: "Paterna, Comunitat Valenciana, España", lat: 39.5029, lng: -0.4389 },
  // ── Grandes ciudades de España ────────────────────────────────────────────
  { id: 61, city: "Madrid", region: "Comunidad de Madrid", country: "España", label: "Madrid, Comunidad de Madrid, España", lat: 40.4168, lng: -3.7038 },
  { id: 62, city: "Barcelona", region: "Cataluña", country: "España", label: "Barcelona, Cataluña, España", lat: 41.3851, lng: 2.1734 },
  { id: 63, city: "Sevilla", region: "Andalucía", country: "España", label: "Sevilla, Andalucía, España", lat: 37.3891, lng: -5.9845 },
  { id: 64, city: "Zaragoza", region: "Aragón", country: "España", label: "Zaragoza, Aragón, España", lat: 41.6488, lng: -0.8891 },
  { id: 65, city: "Málaga", region: "Andalucía", country: "España", label: "Málaga, Andalucía, España", lat: 36.7213, lng: -4.4214 },
  { id: 66, city: "Bilbao", region: "País Vasco", country: "España", label: "Bilbao, País Vasco, España", lat: 43.2630, lng: -2.9350 },
  { id: 67, city: "Granada", region: "Andalucía", country: "España", label: "Granada, Andalucía, España", lat: 37.1773, lng: -3.5986 },
  { id: 68, city: "Córdoba", region: "Andalucía", country: "España", label: "Córdoba, Andalucía, España", lat: 37.8882, lng: -4.7794 },
  { id: 69, city: "Palma de Mallorca", region: "Islas Baleares", country: "España", label: "Palma de Mallorca, Islas Baleares, España", lat: 39.5696, lng: 2.6502 },
  { id: 70, city: "Las Palmas de Gran Canaria", region: "Canarias", country: "España", label: "Las Palmas de Gran Canaria, Canarias, España", lat: 28.1235, lng: -15.4366 },
  { id: 71, city: "Santa Cruz de Tenerife", region: "Canarias", country: "España", label: "Santa Cruz de Tenerife, Canarias, España", lat: 28.4636, lng: -16.2518 },
  { id: 72, city: "Marbella", region: "Andalucía", country: "España", label: "Marbella, Andalucía, España", lat: 36.5101, lng: -4.8825 },
  { id: 73, city: "Estepona", region: "Andalucía", country: "España", label: "Estepona, Andalucía, España", lat: 36.4270, lng: -5.1460 },
  { id: 74, city: "Fuengirola", region: "Andalucía", country: "España", label: "Fuengirola, Andalucía, España", lat: 36.5400, lng: -4.6258 },
  { id: 75, city: "Torremolinos", region: "Andalucía", country: "España", label: "Torremolinos, Andalucía, España", lat: 36.6227, lng: -4.4997 },
  { id: 76, city: "San Sebastián", region: "País Vasco", country: "España", label: "San Sebastián, País Vasco, España", lat: 43.3183, lng: -1.9812 },
  { id: 77, city: "Vitoria-Gasteiz", region: "País Vasco", country: "España", label: "Vitoria-Gasteiz, País Vasco, España", lat: 42.8467, lng: -2.6727 },
  { id: 78, city: "A Coruña", region: "Galicia", country: "España", label: "A Coruña, Galicia, España", lat: 43.3623, lng: -8.4115 },
  { id: 79, city: "Vigo", region: "Galicia", country: "España", label: "Vigo, Galicia, España", lat: 42.2314, lng: -8.7124 },
  { id: 80, city: "Salamanca", region: "Castilla y León", country: "España", label: "Salamanca, Castilla y León, España", lat: 40.9701, lng: -5.6635 },
];
