// Auto-generated by `supabase gen types typescript` (via Supabase MCP).
// Re-run after schema changes: keep in sync with /supabase/migrations.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      leads: {
        Row: {
          assigned_to: string | null;
          budget: number | null;
          contact_methods: string[] | null;
          created_at: string | null;
          email: string;
          id: string;
          language: string | null;
          message: string | null;
          name: string;
          phone: string | null;
          services: string[] | null;
          source: string | null;
          status: string | null;
          urgency: string | null;
          workspace_id: string | null;
        };
        Insert: {
          assigned_to?: string | null;
          budget?: number | null;
          contact_methods?: string[] | null;
          created_at?: string | null;
          email: string;
          id?: string;
          language?: string | null;
          message?: string | null;
          name: string;
          phone?: string | null;
          services?: string[] | null;
          source?: string | null;
          status?: string | null;
          urgency?: string | null;
          workspace_id?: string | null;
        };
        Update: {
          assigned_to?: string | null;
          budget?: number | null;
          contact_methods?: string[] | null;
          created_at?: string | null;
          email?: string;
          id?: string;
          language?: string | null;
          message?: string | null;
          name?: string;
          phone?: string | null;
          services?: string[] | null;
          source?: string | null;
          status?: string | null;
          urgency?: string | null;
          workspace_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "leads_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      properties: {
        Row: {
          address: string | null;
          bathrooms: number | null;
          bedrooms: number | null;
          city: string;
          created_at: string | null;
          description: string | null;
          featured: boolean | null;
          features: string[] | null;
          id: string;
          images: Json | null;
          lat: number | null;
          lng: number | null;
          loc: string;
          m2: number | null;
          meta_desc: string | null;
          meta_title: string | null;
          price: number;
          published_at: string | null;
          slug: string;
          status: string | null;
          title: string;
          type: string;
          updated_at: string | null;
          workspace_id: string;
        };
        Insert: {
          address?: string | null;
          bathrooms?: number | null;
          bedrooms?: number | null;
          city: string;
          created_at?: string | null;
          description?: string | null;
          featured?: boolean | null;
          features?: string[] | null;
          id?: string;
          images?: Json | null;
          lat?: number | null;
          lng?: number | null;
          loc: string;
          m2?: number | null;
          meta_desc?: string | null;
          meta_title?: string | null;
          price: number;
          published_at?: string | null;
          slug: string;
          status?: string | null;
          title: string;
          type: string;
          updated_at?: string | null;
          workspace_id: string;
        };
        Update: {
          address?: string | null;
          bathrooms?: number | null;
          bedrooms?: number | null;
          city?: string;
          created_at?: string | null;
          description?: string | null;
          featured?: boolean | null;
          features?: string[] | null;
          id?: string;
          images?: Json | null;
          lat?: number | null;
          lng?: number | null;
          loc?: string;
          m2?: number | null;
          meta_desc?: string | null;
          meta_title?: string | null;
          price?: number;
          published_at?: string | null;
          slug?: string;
          status?: string | null;
          title?: string;
          type?: string;
          updated_at?: string | null;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "properties_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      reviews: {
        Row: {
          author_name: string;
          body: string;
          city: string | null;
          created_at: string | null;
          id: string;
          rating: number;
          services: string[] | null;
          status: string | null;
          workspace_id: string | null;
        };
        Insert: {
          author_name: string;
          body: string;
          city?: string | null;
          created_at?: string | null;
          id?: string;
          rating: number;
          services?: string[] | null;
          status?: string | null;
          workspace_id?: string | null;
        };
        Update: {
          author_name?: string;
          body?: string;
          city?: string | null;
          created_at?: string | null;
          id?: string;
          rating?: number;
          services?: string[] | null;
          status?: string | null;
          workspace_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      workspace_members: {
        Row: {
          created_at: string | null;
          id: string;
          role: string | null;
          user_id: string;
          workspace_id: string;
        };
        Insert: {
          created_at?: string | null;
          id?: string;
          role?: string | null;
          user_id: string;
          workspace_id: string;
        };
        Update: {
          created_at?: string | null;
          id?: string;
          role?: string | null;
          user_id?: string;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "workspace_members_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      workspaces: {
        Row: {
          created_at: string | null;
          id: string;
          name: string;
        };
        Insert: {
          created_at?: string | null;
          id?: string;
          name: string;
        };
        Update: {
          created_at?: string | null;
          id?: string;
          name?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
};
